
export const defaultShoppingItems: string[] = [
    "Süt",
    "Ekmek",
    "Yumurta",
    "Peynir",
    "Zeytin",
    "Domates",
    "Salatalık",
    "Biber",
    "Soğan",
    "Sarımsak",
    "Patates",
    "Elma",
    "Muz",
    "Portakal",
    "Limon",
    "Tavuk",
    "Kıyma",
    "Balık",
    "Pirinç",
    "Bulgur",
    "Makarna",
    "Salça",
    "Sıvı Yağ",
    "Tereyağı",
    "Un",
    "Şeker",
    "Tuz",
    "Çay",
    "Kahve",
    "Yoğurt",
    "Su",
    "Meyve Suyu",
    "Deterjan",
    "Çamaşır Suyu",
    "Bulaşık Deterjanı",
    "Şampuan",
    "Sabun",
    "Diş Macunu",
    "Tuvalet Kağıdı",
    "Kağıt Havlu",
];
